# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Test Cases

# Run on all branch
on:
  push:
    paths:
      - '.github/workflows/run-test.yml'
      - 'docs/**'
      - 'src/**'
      - 'test/**'
  pull_request:
    paths:
      - '.github/workflows/run-test.yml'
      - 'docs/**'
      - 'src/**'
      - 'test/**'

jobs:
  test:
    name: 'Test'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    # See https://docs.cypress.io/guides/continuous-integration/github-actions
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          component: true
          browser: ${{ matrix.browser }}
