name: Run Test Cases

# Run on all branch
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    name: 'Test'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Cache node modules
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install NPM dependencies
      - name: Install dependencies
        run: npm ci

      # Cache Cypress files
      - name: Cache Cypress
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-${{ github.run_id }}

      # Cypress run
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          component: true
          browser: ${{ matrix.browser }}
        env:
          # Disable GPU acceleration for headless browsers
          CYPRESS_runTestsInHeadlessMode: '--disable-gpu'
