name: Run Test Cases

# Run on all branch
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    name: 'Test'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies
      - name: Install dependencies
        run: npm ci

      # Cache Cypress files
      - name: Cache Cypress
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ matrix.browser }}-${{ hashFiles('package-lock.json') }}-${{ github.run_id }}

      # Verify Firefox installation (optional)
      - name: Verify Firefox installation
        run: firefox --version

      # Run Cypress tests in headless mode with browser cache
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: ${{ matrix.browser }}
        env:
          MOZ_HEADLESS: 1  # Ensure Firefox runs in headless mode
          CYPRESS_runTestsInHeadlessMode: '--disable-gpu'
          CYPRESS_defaultCommandTimeout: 60000
          CYPRESS_pageLoadTimeout: 60000