name: Run Test Cases

# Run on all branch
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    name: 'Test'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies
      - name: Install dependencies
        run: npm ci

      # Cache Cypress files
      - name: Cache Cypress
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-${{ github.run_id }}

      # Install and start Xvfb
      - name: Install Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          export DISPLAY=:99.0
          Xvfb :99 -screen 0 1280x1024x16 &

      # Cypress run
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          component: true
          browser: ${{ matrix.browser }}
        env:
          # Disable GPU acceleration for headless browsers
          CYPRESS_runTestsInHeadlessMode: '--disable-gpu'
          MOZ_HEADLESS: 1
          MOZ_X11_EGL: 1
          CYPRESS_defaultCommandTimeout: 60000
          CYPRESS_pageLoadTimeout: 60000
