name: Run Test Cases

# Run on all branch
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: 'Test'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, edge]

    steps:
      # Checkout latest code
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies
      - name: Install dependencies
        run: npm ci

      # Cache Cypress files
      - name: Cache Cypress
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-${{ github.run_id }}

      # Run Cypress tests on multiple browsers
      - name: Cypress run
        uses: cypress-io/github-action@v5 # Ensure latest Cypress GitHub Action
        with:
          component: true
          browser: ${{ matrix.browser }}
